lexik_jwt_authentication:
    api_platform:
        check_path: /auth
        username_path: email
        password_path: security.credentials.password

    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'

