vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        products:
            uri_prefix: /images/user
            upload_destination: '%kernel.project_dir%/public/media/user'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer