# api/config/packages/vich_uploader.yaml

vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        media_bloc:
            uri_prefix: /media/bloc
            upload_destination: '%kernel.project_dir%/public/media/bloc'
            # Will rename uploaded files using a uniqueid as a prefix.
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer